services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_URI: mongodb://db
      MONGO_DB: app
    ports:
      - "8080:8080"

  db:
    image: mongodb:latest
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data: